# It's not actually used just yet.
---
Algorithms and Data Structures I:
  level: 4
Discrete Mathematics:
  level: 4
Fundamentals of Computer Science:
  level: 4
How Computers Work:
  level: 4
Introduction to Programming I:
  level: 4
Numerical Mathematics:
  level: 4
Introduction to Programming II:
  level: 4
Web Development:
  level: 4
Algorithms and Data Structures II:
  level: 5
Agile Software Projects:
  level: 5
Computer Security:
  level: 5
Databases networks and the web:
  level: 5
Graphics Programming:
  level: 5
Object Oriented Programming:
  level: 5
Programming with Data:
  level: 5
Software Design and Development:
  level: 5
Databases and Advanced Data Techniques:
  level: 6
Machine Learning and Neural Networks:
  level: 6
Artificial Intelligence:
  level: 6
Intelligent Signal Processing:
  level: 6
Natural Language Processing:
  level: 6
Final Project:
  level: 6
